In [1]:
import pandas as pd
import numpy as np

#### Data Description
##### Flight : ID of Flight
##### Time : Departure Time
##### Length : Length of Flight
##### Airline : Airline ID
##### AirportFrom : Which airport the flight flew from
##### AirportTo : Which airport the flight flew to
##### DayOfWeek : Day of the week of the flight
##### Class : Delayed(1) or Not(0)

In [2]:
df = pd.read_csv("final_dataset_airline_delay.csv")
df

Flight      Time    Length Airline AirportFrom AirportTo  DayOfWeek  \
0       2313.0  0.899930  0.215267      DL         ATL       HOU          1   
1       6948.0  0.244927  0.222901      OO         COS       ORD          4   
2       1247.0  0.811756  0.218321      B6         BOS       CLT          3   
3         31.0  0.979706  0.525191      US         OGG       PHX          6   
4        563.0  0.477257  0.149618      FL         BMI       ATL          4   
...        ...       ...       ...     ...         ...       ...        ...   
539377  6973.0  0.363891  0.109924      OO         GEG       SEA          5   
539378  1264.0  0.384885  0.175573      WN         LAS       DEN          4   
539379  5209.0  0.571728  0.112977      EV         CAE       ATL          2   
539380   607.0  0.493352  0.099237      WN         BWI       BUF          4   
539381  6377.0  0.531840  0.083969      OO         CPR       DEN          2   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
539377      1  
539378      1  
539379      1  
539380      1  
539381      1  

[539382 rows x 8 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 539382 entries, 0 to 539381
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   Flight       539382 non-null  float64
 1   Time         539382 non-null  float64
 2   Length       539382 non-null  float64
 3   Airline      539382 non-null  object 
 4   AirportFrom  539382 non-null  object 
 5   AirportTo    539382 non-null  object 
 6   DayOfWeek    539382 non-null  int64  
 7   Class        539382 non-null  int64  
dtypes: float64(3), int64(2), object(3)
memory usage: 32.9+ MB


In [4]:
df.describe()

Flight           Time         Length      DayOfWeek  \
count  539382.000000  539382.000000  539382.000000  539382.000000   
mean     2427.927988       0.554743       0.201835       3.929666   
std      2067.431700       0.194574       0.107049       1.914666   
min         1.000000       0.000000       0.000000       1.000000   
25%       712.000000       0.388383       0.123664       2.000000   
50%      1809.000000       0.549335       0.175573       4.000000   
75%      3745.000000       0.717285       0.247328       5.000000   
max      7814.000000       1.000000       1.000000       7.000000   

               Class  
count  539382.000000  
mean        0.445443  
std         0.497015  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

In [5]:
df.isnull().sum()

Flight         0
Time           0
Length         0
Airline        0
AirportFrom    0
AirportTo      0
DayOfWeek      0
Class          0
dtype: int64

In [6]:
df.drop('Flight', axis=1, inplace=True)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
df = pd.get_dummies(data=df, columns=['Airline','AirportFrom','AirportTo'])

In [8]:
X = df.drop(['Class'], axis=1)
y = df.Class
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30, random_state=40)

In [9]:
df

Time    Length  DayOfWeek  Class  Airline_9E  Airline_AA  \
0       0.899930  0.215267          1      0           0           0   
1       0.244927  0.222901          4      0           0           0   
2       0.811756  0.218321          3      0           0           0   
3       0.979706  0.525191          6      0           0           0   
4       0.477257  0.149618          4      0           0           0   
...          ...       ...        ...    ...         ...         ...   
539377  0.363891  0.109924          5      1           0           0   
539378  0.384885  0.175573          4      1           0           0   
539379  0.571728  0.112977          2      1           0           0   
539380  0.493352  0.099237          4      1           0           0   
539381  0.531840  0.083969          2      1           0           0   

        Airline_AS  Airline_B6  Airline_CO  Airline_DL  ...  AirportTo_TXK  \
0                0           0           0           1  ...              0   
1                0           0           0           0  ...              0   
2                0           1           0           0  ...              0   
3                0           0           0           0  ...              0   
4                0           0           0           0  ...              0   
...            ...         ...         ...         ...  ...            ...   
539377           0           0           0           0  ...              0   
539378           0           0           0           0  ...              0   
539379           0           0           0           0  ...              0   
539380           0           0           0           0  ...              0   
539381           0           0           0           0  ...              0   

        AirportTo_TYR  AirportTo_TYS  AirportTo_UTM  AirportTo_VLD  \
0                   0              0              0              0   
1                   0              0              0              0   
2                   0              0              0              0   
3                   0              0              0              0   
4                   0              0              0              0   
...               ...            ...            ...            ...   
539377              0              0              0              0   
539378              0              0              0              0   
539379              0              0              0              0   
539380              0              0              0              0   
539381              0              0              0              0   

        AirportTo_VPS  AirportTo_WRG  AirportTo_XNA  AirportTo_YAK  \
0                   0              0              0              0   
1                   0              0              0              0   
2                   0              0              0              0   
3                   0              0              0              0   
4                   0              0              0              0   
...               ...            ...            ...            ...   
539377              0              0              0              0   
539378              0              0              0              0   
539379              0              0              0              0   
539380              0              0              0              0   
539381              0              0              0              0   

        AirportTo_YUM  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  
...               ...  
539377              0  
539378              0  
539379              0  
539380              0  
539381              0  

[539382 rows x 608 columns]

### KNN

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
knn = KNeighborsClassifier(p=2, metric='minkowski', n_neighbors=5)

In [12]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [13]:
y_knn_pred = knn.predict(X_test)
print(y_knn_pred)

[1 0 1 ... 1 0 0]


In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_knn = confusion_matrix(y_test, y_knn_pred)
print (cm_knn)
acc_knn = accuracy_score(y_test, y_knn_pred)
print (acc_knn)

[[61918 27820]
 [33220 38857]]
0.6227790995890369


### Naive Bayes

#### Gaussian Naive Bayes

In [15]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

In [16]:
y_pred_nb = nb.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_nb)
print(cm)
acc_nb = accuracy_score(y_test, y_pred_nb)
print (acc_nb * 100, "%")


[[19000 70738]
 [ 9194 62883]]
50.60284893242283 %


#### Multinomial Naive Bayes

In [18]:
from sklearn.naive_bayes import MultinomialNB
mb = MultinomialNB()
mb.fit(X_train, y_train)

MultinomialNB()

In [19]:
y_pred_mb = mb.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_mb)
print(cm)
acc_mb = accuracy_score(y_test, y_pred_mb)
print (acc_mb * 100, "%")


[[70639 19099]
 [40859 31218]]
62.94657479220097 %


#### Complement Naive Bayes

In [21]:
from sklearn.naive_bayes import ComplementNB
cb = ComplementNB()
cb.fit(X_train, y_train)

ComplementNB()

In [22]:
y_pred_cb = cb.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_cb)
print(cm)
acc_cb = accuracy_score(y_test, y_pred_cb)
print (acc_cb * 100, "%")


[[63059 26679]
 [34973 37104]]
61.89970027500541 %


####  Bernoulli Naive Bayes

In [24]:
from sklearn.naive_bayes import BernoulliNB
bb = BernoulliNB()
bb.fit(X_train, y_train)

BernoulliNB()

In [25]:
y_pred_bb = bb.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_bb)
print(cm)
acc_bb = accuracy_score(y_test, y_pred_bb)
print (acc_bb * 100, "%")

[[71437 18301]
 [41770 30307]]
62.8767419584093 %


### SVM

In [16]:
df_svm = df.sample(frac=0.05)

In [17]:
X = df_svm.drop(['Class'], axis=1)
y = df_svm.Class
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30, random_state=40)

In [18]:
from sklearn.svm import SVC
svc_rbf = SVC(kernel = 'sigmoid', random_state = 0)
svc_rbf.fit(X_train, y_train)

SVC(kernel='sigmoid', random_state=0)

In [19]:
y_pred_svc_rbf = svc_rbf.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_svc_rbf)
print (cm)
acc_svc_rbf = accuracy_score(y_test, y_pred_svc_rbf)
print (acc_svc_rbf * 100, "%" )

[[2541 1905]
 [2037 1608]]
51.279199110122356 %


### Decision Tree

In [10]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [11]:
y_pred = dt.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print (cm)
acc_dt = accuracy_score(y_test, y_pred)
print (f"{acc_dt * 100} %")

[[64166 25572]
 [37542 34535]]
60.99619936347062 %
